import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  outer: {
    minHeight: '100vh',
    backgroundColor: '#F9F9FB',
    color: '#000000',
  },
  header: {
    backgroundColor: '#FFFFFF',
    borderBottom: '1px solid #E5E7EB',
    padding: '12px 24px',
  },
  headerInner: {
    maxWidth: '760px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandTitle: {
    fontWeight: 'bold',
    fontSize: '16px',
    color: '#111827',
  },
  adminNavButton: {
    backgroundColor: '#F3F4F6',
    border: '1px solid #E5E7EB',
    padding: '6px 14px',
    borderRadius: '6px',
    fontSize: '13px',
    cursor: 'pointer',
    fontWeight: 500,
  },
  mainContainer: {
    maxWidth: '720px',
    margin: '0 auto',
    padding: '24px 16px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  heading: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
  },
  subtext: {
    fontSize: '14px',
    color: '#6B7280',
    margin: 0,
  },
  cardList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '12px',
  },
  initialBadge: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    backgroundColor: '#F3F4F6',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '18px',
  },
  cardTitle: {
    fontWeight: 600,
    fontSize: '16px',
  },
  cardSub: {
    fontSize: '13px',
    color: '#6B7280',
    marginTop: '2px',
  },
  arrowIcon: {
    fontSize: '18px',
    color: '#9CA3AF',
  },
  backLink: {
    background: 'none',
    border: 'none',
    color: '#6B7280',
    fontSize: '14px',
    cursor: 'pointer',
    padding: '4px 0',
    textAlign: 'left',
  },
  unitHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '20px',
  },
  unitBackButton: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#EFEFF2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  unitHeaderTitle: {
    fontSize: '17px',
    fontWeight: 600,
    color: '#111',
  },
  subTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#111',
    marginBottom: '16px',
    marginTop: 0,
  },
  unitCard: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    padding: '16px',
    marginBottom: '12px',
    alignItems: 'center',
    border: '1px solid #EFEFF2',
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.02)',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease',
  },
  unitNumberBadge: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '14px',
    flexShrink: 0,
  },
  unitNumberText: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#333',
  },
  unitInfo: {
    flex: 1,
  },
  unitName: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#111',
    marginBottom: '3px',
  },
  unitQuestionText: {
    fontSize: '13px',
    color: '#777',
  },
  unitDetailHeaderTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#111',
    maxWidth: '320px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    textAlign: 'center',
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '16px',
    border: '1px solid #EFEFF2',
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.02)',
  },
  heroBadge: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '12px',
  },
  heroBadgeText: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#111',
  },
  heroTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
    textAlign: 'center',
    marginBottom: '6px',
  },
  heroQuestionCount: {
    fontSize: '14px',
    color: '#777',
  },
  rulesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '20px',
    border: '1px solid #EFEFF2',
  },
  rulesCardTitle: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#111',
    marginBottom: '14px',
  },
  ruleItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '10px',
  },
  ruleDot: {
    width: '6px',
    height: '6px',
    borderRadius: '3px',
    backgroundColor: '#111',
    marginRight: '10px',
    flexShrink: 0,
  },
  ruleText: {
    fontSize: '14px',
    color: '#444',
  },
  footerContainer: {
    position: 'fixed',
    bottom: '64px',
    left: 0,
    right: 0,
    backgroundColor: '#F9F9FB',
    padding: '16px 20px',
    borderTop: '1px solid #EFEFF2',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    zIndex: 990,
  },
  startButton: {
    maxWidth: '600px',
    width: '100%',
    backgroundColor: '#111',
    color: '#FFF',
    borderRadius: '14px',
    height: '52px',
    border: 'none',
    fontSize: '16px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '10px',
    transition: 'background-color 0.15s ease',
  },
  footerInfoRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerInfoText: {
    fontSize: '12px',
    color: '#666',
  },
  quizNavHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  quizBackButton: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#EFEFF2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  quizMenuButton: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#EFEFF2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  quizHeaderCounter: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#111',
  },
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '20px',
    marginBottom: '16px',
    border: '1px solid #EFEFF2',
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.02)',
  },
  questionLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#777',
    marginBottom: '8px',
    letterSpacing: '0.5px',
  },
  questionText: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#111',
    lineHeight: '22px',
  },
  optionCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    padding: '16px',
    marginBottom: '10px',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  optionCardSelected: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  radioCircle: {
    width: '20px',
    height: '20px',
    borderRadius: '10px',
    border: '2px solid #CCC',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '12px',
    flexShrink: 0,
  },
  radioCircleSelected: {
    borderColor: '#FFF',
  },
  radioInnerDot: {
    width: '8px',
    height: '8px',
    borderRadius: '4px',
    backgroundColor: '#FFF',
  },
  optionKey: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#333',
    marginRight: '10px',
    width: '16px',
    flexShrink: 0,
  },
  optionKeySelected: {
    color: '#FFF',
  },
  optionText: {
    fontSize: '14px',
    color: '#333',
    flex: 1,
  },
  optionTextSelected: {
    color: '#FFF',
  },
  actionButton: {
    maxWidth: '600px',
    width: '100%',
    backgroundColor: '#111',
    color: '#FFF',
    borderRadius: '14px',
    height: '52px',
    border: 'none',
    fontSize: '16px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'all 0.15s ease',
  },
  explanationBox: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #E5E7EB',
    borderRadius: '14px',
    padding: '16px',
    marginTop: '12px',
    marginBottom: '16px',
  },
  explanationTitle: {
    fontWeight: 'bold',
    fontSize: '14px',
    marginBottom: '6px',
  },
  explanationText: {
    fontSize: '13px',
    lineHeight: '20px',
    color: '#4B5563',
  },
  resultBox: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #E5E7EB',
    borderRadius: '10px',
    padding: '28px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  resultStatsRow: {
    display: 'flex',
    justifyContent: 'space-around',
    gap: '12px',
  },
  resultCard: {
    flex: 1,
    padding: '16px',
    border: '1px solid #E5E7EB',
    borderRadius: '8px',
    backgroundColor: '#F9F9FB',
  },
  resultActions: {
    display: 'flex',
    gap: '12px',
  },
  primaryActionBtn: {
    flex: 1,
    minHeight: '50px',
    backgroundColor: '#111827',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  secondaryActionBtn: {
    flex: 1,
    minHeight: '50px',
    backgroundColor: '#FFFFFF',
    color: '#111827',
    border: '1px solid #E5E7EB',
    borderRadius: '8px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  homeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  greetingSub: {
    fontSize: '16px',
    color: '#666',
  },
  greetingName: {
    fontSize: '26px',
    fontWeight: 'bold',
    color: '#111',
  },
  profileButton: {
    width: '42px',
    height: '42px',
    borderRadius: '21px',
    backgroundColor: '#EFEFF2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
  },
  subQuestion: {
    fontSize: '15px',
    color: '#555',
    marginBottom: '20px',
  },
  goalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '20px',
    marginBottom: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.04)',
    border: '1px solid #EFEFF2',
  },
  goalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  goalTitle: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#333',
  },
  goalTargetText: {
    fontSize: '13px',
    color: '#777',
  },
  goalNumbers: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#111',
    marginBottom: '12px',
  },
  goalTotal: {
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#777',
  },
  progressBarBackground: {
    height: '8px',
    backgroundColor: '#EFEFF2',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#111',
    borderRadius: '4px',
    transition: 'width 0.3s ease',
  },
  goalFooterText: {
    fontSize: '12px',
    color: '#666',
  },
  sectionHeader: {
    marginBottom: '12px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
  },
  seeAllButton: {
    background: 'none',
    border: 'none',
    color: '#111',
    fontWeight: 600,
    fontSize: '13px',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '6px',
  },
  topTabBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  tabContainer: {
    display: 'flex',
    backgroundColor: '#EFEFF2',
    borderRadius: '10px',
    padding: '4px',
    gap: '4px',
  },
  tabButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#666',
    fontWeight: 500,
    fontSize: '13px',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  tabButtonActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    border: 'none',
    backgroundColor: '#FFFFFF',
    color: '#111',
    fontWeight: 600,
    fontSize: '13px',
    borderRadius: '8px',
    cursor: 'pointer',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  mainTitle: {
    fontSize: '26px',
    fontWeight: 'bold',
    color: '#111',
    marginBottom: '20px',
    marginTop: 0,
  },
  categoryTitle: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#666',
    marginBottom: '12px',
    marginTop: '4px',
  },
  subjectCard: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    padding: '16px',
    marginBottom: '12px',
    alignItems: 'center',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    boxShadow: '0 1px 3px rgba(0,0,0,0.02)',
  },
  iconContainer: {
    width: '42px',
    height: '42px',
    borderRadius: '10px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '14px',
    flexShrink: 0,
  },
  subjectInfo: {
    flex: 1,
  },
  subjectRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2px',
  },
  subjectTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#111',
  },
  unitText: {
    fontSize: '13px',
    color: '#777',
    marginBottom: '8px',
  },
  progressRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressBarBg: {
    flex: 1,
    height: '6px',
    backgroundColor: '#EFEFF2',
    borderRadius: '3px',
    overflow: 'hidden',
    marginRight: '10px',
  },
  cardProgressBarFill: {
    height: '100%',
    backgroundColor: '#111',
    borderRadius: '3px',
    transition: 'width 0.3s ease',
  },
  percentageText: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#555',
    width: '32px',
    textAlign: 'right',
  },
  statusCard: {
    padding: '24px',
    borderRadius: '16px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '16px',
    borderWidth: '1px',
    borderStyle: 'solid',
    textAlign: 'center',
  },
  statusCardCorrect: {
    backgroundColor: '#F0FDF4',
    borderColor: '#DCFCE7',
  },
  statusCardWrong: {
    backgroundColor: '#FFF2F2',
    borderColor: '#FEE2E2',
  },
  statusIconContainer: {
    width: '56px',
    height: '56px',
    borderRadius: '28px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '12px',
  },
  statusIconCorrect: {
    backgroundColor: '#2E7D32',
  },
  statusIconWrong: {
    backgroundColor: '#D32F2F',
  },
  statusTitle: {
    fontSize: '18px',
    fontWeight: 700,
    color: '#111',
    marginBottom: '4px',
  },
  statusSubtitle: {
    fontSize: '14px',
    color: '#666',
  },
  feedbackExplanationCard: {
    backgroundColor: '#FFF',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#EFEFF2',
    borderRadius: '16px',
    padding: '20px',
  },
  feedbackExplanationLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#999',
    textTransform: 'uppercase',
    marginBottom: '8px',
    letterSpacing: '0.5px',
  },
  feedbackExplanationText: {
    fontSize: '14px',
    color: '#333',
    lineHeight: '22px',
    whiteSpace: 'pre-line',
  },
  feedbackBottomBar: {
    position: 'fixed',
    bottom: '64px',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    padding: '12px 20px',
    borderTop: '1px solid #E5E7EB',
    display: 'flex',
    justifyContent: 'center',
    zIndex: 990,
    boxShadow: '0 -3px 12px rgba(0, 0, 0, 0.05)',
  },
  feedbackNextButton: {
    maxWidth: '440px',
    width: '100%',
    backgroundColor: '#18181B',
    height: '52px',
    borderRadius: '14px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFFFFF',
    fontSize: '16px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
    transition: 'all 0.15s ease',
  },
  resultCardNew: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '16px',
    border: '1px solid #EFEFF2',
  },
  resultMainTitleNew: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
    marginBottom: '20px',
  },
  circleContainerNew: {
    width: '130px',
    height: '130px',
    borderRadius: '65px',
    border: '8px solid #111',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '24px',
  },
  scoreTextNew: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#111',
  },
  percentageTextNew: {
    fontSize: '12px',
    color: '#666',
    marginTop: '2px',
  },
  statsRowNew: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTop: '1px solid #EFEFF2',
    paddingTop: '16px',
  },
  statItemNew: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  statDotNew: {
    width: '8px',
    height: '8px',
    borderRadius: '4px',
    marginBottom: '4px',
  },
  statLabelNew: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '2px',
  },
  statValueNew: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#111',
  },
  statDividerNew: {
    width: '1px',
    height: '24px',
    backgroundColor: '#EFEFF2',
  },
  errorBannerNew: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    padding: '14px',
    marginBottom: '20px',
    border: '1px solid #EFEFF2',
    justifyContent: 'center',
  },
  errorBannerTextNew: {
    fontSize: '13px',
    color: '#555',
  },
  resultPrimaryButton: {
    backgroundColor: '#111',
    borderRadius: '14px',
    height: '52px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFF',
    fontSize: '16px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    width: '100%',
  },
  resultSecondaryButton: {
    backgroundColor: '#EFEFF2',
    borderRadius: '14px',
    height: '52px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#111',
    fontSize: '16px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    width: '100%',
  },
  resultOutlineButton: {
    backgroundColor: 'transparent',
    borderRadius: '14px',
    height: '52px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#555',
    fontSize: '16px',
    fontWeight: 600,
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    width: '100%',
  },
  errorHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '20px',
  },
  errorMainTitle: {
    fontSize: '26px',
    fontWeight: 'bold',
    color: '#111',
    margin: 0,
    marginBottom: '2px',
  },
  errorSubCountText: {
    fontSize: '14px',
    color: '#666',
  },
  errorFilterButton: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: '8px 14px',
    borderRadius: '10px',
    border: '1px solid #EFEFF2',
    fontSize: '14px',
    fontWeight: 600,
    color: '#111',
    cursor: 'pointer',
  },
  errorCardWeb: {
    display: 'flex',
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    padding: '16px',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
  },
  errorCardLeft: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
  },
  errorIconContainer: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '12px',
    flexShrink: 0,
  },
  errorInfoContainer: {
    flex: 1,
  },
  errorSubjectName: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#111',
    marginBottom: '2px',
  },
  errorUnitName: {
    fontSize: '13px',
    color: '#555',
    marginBottom: '2px',
  },
  errorQNumberText: {
    fontSize: '12px',
    color: '#777',
  },
  errorCardRight: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  errorBadgeRow: {
    display: 'flex',
    gap: '6px',
  },
  errorWrongBadge: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#D32F2F',
    backgroundColor: '#FFDCDC',
    padding: '2px 6px',
    borderRadius: '6px',
  },
  errorCorrectBadge: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#2E7D32',
    backgroundColor: '#E8F5E9',
    padding: '2px 6px',
    borderRadius: '6px',
  },
  searchContainerDashboard: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    border: '1px solid #EFEFF2',
    borderRadius: '10px',
    padding: '0 12px',
    height: '40px',
    width: '240px',
  },
  searchInputDashboard: {
    border: 'none',
    outline: 'none',
    fontSize: '13px',
    color: '#111',
    width: '100%',
    backgroundColor: 'transparent',
  },
  scrollBodyDashboard: {
    display: 'flex',
    gap: '24px',
    marginTop: '20px',
  },
  leftColumnDashboard: {
    flex: 1.4,
  },
  welcomeSectionDashboard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: '20px',
  },
  welcomeTitleDashboard: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#111',
    margin: 0,
    marginBottom: '4px',
  },
  welcomeSubDashboard: {
    fontSize: '15px',
    color: '#666',
  },
  dateBadgeDashboard: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1px solid #EFEFF2',
  },
  dateTextDashboard: {
    fontSize: '13px',
    color: '#444',
    fontWeight: 500,
  },
  goalCardDashboard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '24px',
    marginBottom: '24px',
    border: '1px solid #EFEFF2',
  },
  goalHeaderRowDashboard: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  goalCardTitleDashboard: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#333',
  },
  goalTargetTextDashboard: {
    fontSize: '13px',
    color: '#777',
  },
  goalBigNumbersDashboard: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#111',
    marginBottom: '14px',
  },
  goalTotalDimDashboard: {
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#777',
  },
  progressBarBgDashboard: {
    height: '8px',
    backgroundColor: '#EFEFF2',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  progressBarFillDashboard: {
    height: '100%',
    backgroundColor: '#111',
    borderRadius: '4px',
    transition: 'width 0.3s ease',
  },
  goalFooterInfoDashboard: {
    fontSize: '12px',
    color: '#666',
  },
  sectionHeaderRowDashboard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  sectionHeadingDashboard: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
  },
  seeAllTextDashboard: {
    fontSize: '13px',
    color: '#666',
    fontWeight: 600,
  },
  categorySubHeadingDashboard: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#666',
    marginBottom: '10px',
  },
  gridRowDashboard: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginBottom: '12px',
  },
  gridCardDashboard: {
    display: 'flex',
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    padding: '16px',
    alignItems: 'center',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease, transform 0.15s ease',
  },
  cardIconBoxDashboard: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '12px',
    flexShrink: 0,
  },
  cardTitleRowDashboard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2px',
  },
  cardSubjectTitleDashboard: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#111',
  },
  cardSubInfoDashboard: {
    fontSize: '12px',
    color: '#777',
    marginBottom: '8px',
  },
  miniBarBgDashboard: {
    height: '4px',
    backgroundColor: '#EFEFF2',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  miniBarFillDashboard: {
    height: '100%',
    backgroundColor: '#111',
    borderRadius: '2px',
  },
  percentLabelDashboard: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#444',
    marginLeft: '12px',
  },
  rightColumnDashboard: {
    flex: 1,
  },
  rightWidgetDashboard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '20px',
    marginBottom: '20px',
    border: '1px solid #EFEFF2',
  },
  widgetHeaderRowDashboard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  widgetTitleDashboard: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#111',
  },
  editTextDashboard: {
    fontSize: '13px',
    color: '#666',
    fontWeight: 500,
    cursor: 'pointer',
  },
  planItemDashboard: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#F9F9FB',
    borderRadius: '12px',
    padding: '12px',
    marginBottom: '10px',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
  },
  planNumberDashboard: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#111',
    backgroundColor: '#EFEFF2',
    padding: '6px 8px',
    borderRadius: '8px',
    flexShrink: 0,
  },
  planSubjectDashboard: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#111',
    marginBottom: '2px',
  },
  planDetailDashboard: {
    fontSize: '11px',
    color: '#777',
  },
  startPlanButtonDashboard: {
    backgroundColor: '#111',
    borderRadius: '12px',
    height: '48px',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFF',
    fontSize: '14px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    marginTop: '6px',
    transition: 'opacity 0.15s ease',
  },
  statsGridDashboard: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
  },
  statBoxDashboard: {
    backgroundColor: '#F9F9FB',
    borderRadius: '12px',
    padding: '14px',
    border: '1px solid #EFEFF2',
  },
  statBoxLabelDashboard: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '4px',
  },
  statBoxValDashboard: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
  },
  webContainer: {
    display: 'flex',
    minHeight: '100vh',
    width: '100%',
    backgroundColor: '#F9F9FB',
    color: '#111',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },
  webSidebar: {
    width: '240px',
    minWidth: '240px',
    backgroundColor: '#FFFFFF',
    borderRight: '1px solid #EFEFF2',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: '24px 16px',
    position: 'sticky',
    top: 0,
    height: '100vh',
    boxSizing: 'border-box',
    zIndex: 10,
  },
  sidebarBrand: {
    display: 'flex',
    alignItems: 'center',
    padding: '0 8px 24px 8px',
  },
  sidebarLogoTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
    letterSpacing: '-0.3px',
    lineHeight: 1.1,
  },
  sidebarLogoSubtitle: {
    fontSize: '11px',
    color: '#888',
    marginTop: '2px',
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  sidebarNavItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: '10px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#666',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background-color 0.15s ease, color 0.15s ease',
    width: '100%',
  },
  sidebarNavItemActive: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: '10px',
    backgroundColor: '#F0F0F3',
    border: 'none',
    color: '#111',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
  },
  sidebarQuoteBox: {
    padding: '16px 12px',
    borderTop: '1px solid #F2F2F5',
  },
  quoteMark: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#AAA',
    lineHeight: 1,
    marginBottom: '6px',
  },
  quoteContent: {
    fontSize: '12px',
    color: '#555',
    lineHeight: 1.4,
  },
  quoteFooter: {
    fontSize: '11px',
    color: '#999',
    marginTop: '6px',
  },
  webRightArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    height: '100vh',
    overflow: 'hidden',
  },
  webHeader: {
    height: '64px',
    minHeight: '64px',
    backgroundColor: '#FFFFFF',
    borderBottom: '1px solid #EFEFF2',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 32px',
    boxSizing: 'border-box',
  },
  headerSearchBox: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    border: '1px solid #EFEFF2',
    borderRadius: '10px',
    padding: '0 14px',
    height: '40px',
    width: '320px',
  },
  headerSearchInput: {
    border: 'none',
    outline: 'none',
    fontSize: '13px',
    color: '#111',
    width: '100%',
    backgroundColor: 'transparent',
  },
  headerRightActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  adminNavHeaderButton: {
    backgroundColor: '#F4F4F7',
    border: '1px solid #E5E7EB',
    borderRadius: '9999px',
    padding: '7px 14px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#374151',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
  },
  headerIconBtn: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    backgroundColor: '#FFFFFF',
    border: '1px solid #EFEFF2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
  },
  headerUserBadge: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    border: '1px solid #EFEFF2',
    borderRadius: '10px',
    padding: '6px 12px',
    cursor: 'pointer',
  },
  headerUserAvatar: {
    width: '26px',
    height: '26px',
    borderRadius: '50%',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '8px',
  },
  headerUserName: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#111',
  },
  webMainScroll: {
    flex: 1,
    overflowY: 'auto',
    padding: '28px 32px',
    boxSizing: 'border-box',
  },
  dashboardContainer: {
    display: 'flex',
    gap: '28px',
    maxWidth: '1200px',
    margin: '0 auto',
    width: '100%',
  },
  dashboardLeftCol: {
    flex: 1.45,
    minWidth: 0,
  },
  dashboardRightCol: {
    flex: 1,
    minWidth: 0,
  },
  welcomeRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: '18px',
  },
  welcomeHeading: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#111',
    margin: 0,
    marginBottom: '4px',
  },
  welcomeSubheading: {
    fontSize: '14px',
    color: '#666',
  },
  dateBadgeContainer: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    border: '1px solid #EFEFF2',
    borderRadius: '12px',
    padding: '8px 14px',
  },
  dateBadgeTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#111',
  },
  dateBadgeSub: {
    fontSize: '11px',
    color: '#777',
  },
  goalCardContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '20px 24px',
    marginBottom: '20px',
    border: '1px solid #EFEFF2',
  },
  goalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  goalTargetIconBox: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '10px',
  },
  goalTitleText: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#111',
  },
  goalNumberRow: {
    marginBottom: '12px',
  },
  goalBigNum: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#111',
  },
  goalTotalDim: {
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#777',
  },
  goalProgressBg: {
    height: '8px',
    backgroundColor: '#EFEFF2',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  goalProgressFill: {
    height: '100%',
    backgroundColor: '#111',
    borderRadius: '4px',
    transition: 'width 0.3s ease',
  },
  goalFooterRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    fontSize: '12px',
    color: '#777',
  },
  sectionTitleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
    marginTop: '20px',
  },
  sectionHeadingTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#111',
    margin: 0,
  },
  textLinkBtn: {
    background: 'none',
    border: 'none',
    color: '#666',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    padding: 0,
  },
  categorySubTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#666',
    marginBottom: '10px',
  },
  subjectsGrid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginBottom: '12px',
  },
  dashSubjectCard: {
    display: 'flex',
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    padding: '16px',
    alignItems: 'center',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease, transform 0.15s ease',
  },
  dashSubjectIconBox: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '12px',
    flexShrink: 0,
  },
  dashSubjectTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2px',
  },
  dashSubjectName: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#111',
  },
  dashSubjectUnits: {
    fontSize: '12px',
    color: '#777',
    marginBottom: '6px',
  },
  dashMiniBarBg: {
    height: '4px',
    backgroundColor: '#EFEFF2',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  dashMiniBarFill: {
    height: '100%',
    backgroundColor: '#111',
    borderRadius: '2px',
  },
  dashPercentNum: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#444',
    marginLeft: '12px',
    flexShrink: 0,
  },
  quickAccessTitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#111',
    marginTop: '22px',
    marginBottom: '12px',
  },
  quickAccessRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '10px',
  },
  quickAccessCard: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    padding: '12px 10px',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
  },
  quickAccessIconBox: {
    width: '34px',
    height: '34px',
    borderRadius: '8px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '8px',
    flexShrink: 0,
  },
  quickAccessTitleText: {
    fontSize: '13px',
    fontWeight: 'bold',
    color: '#111',
    lineHeight: 1.2,
  },
  quickAccessSubText: {
    fontSize: '11px',
    color: '#777',
    marginTop: '2px',
  },
  widgetBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '20px',
    marginBottom: '18px',
    border: '1px solid #EFEFF2',
  },
  widgetHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  widgetTitleText: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#111',
  },
  widgetLinkBtn: {
    background: 'none',
    border: 'none',
    fontSize: '13px',
    color: '#666',
    fontWeight: 500,
    cursor: 'pointer',
    padding: 0,
  },
  planItemsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  planCardItem: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#F9F9FB',
    borderRadius: '12px',
    padding: '10px 12px',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
  },
  planNumBadge: {
    fontSize: '13px',
    fontWeight: 'bold',
    color: '#111',
    backgroundColor: '#EFEFF2',
    padding: '6px 8px',
    borderRadius: '8px',
    flexShrink: 0,
  },
  planItemTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#111',
    marginBottom: '2px',
  },
  planItemSub: {
    fontSize: '11px',
    color: '#777',
  },
  startPlanBlackBtn: {
    backgroundColor: '#111',
    borderRadius: '12px',
    height: '44px',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFF',
    fontSize: '14px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    marginTop: '12px',
    transition: 'opacity 0.15s ease',
  },
  statsHorizontalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '8px',
  },
  statMiniBox: {
    backgroundColor: '#F9F9FB',
    borderRadius: '10px',
    padding: '12px 10px',
    border: '1px solid #EFEFF2',
    textAlign: 'center',
  },
  statMiniLabel: {
    fontSize: '11px',
    color: '#666',
    marginBottom: '4px',
    whiteSpace: 'nowrap',
  },
  statMiniVal: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#111',
  },
  errorSubCountMini: {
    fontSize: '12px',
    color: '#777',
    marginBottom: '12px',
    marginTop: '-8px',
  },
  errorItemsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  errorMiniItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 12px',
    backgroundColor: '#F9F9FB',
    borderRadius: '10px',
    border: '1px solid #EFEFF2',
    cursor: 'pointer',
  },
  errorItemTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#111',
  },
  errorItemSub: {
    fontSize: '11px',
    color: '#777',
  },
  errorRedPill: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#EF4444',
    backgroundColor: '#FEE2E2',
    padding: '3px 8px',
    borderRadius: '6px',
  },
  denemeThemeCard: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #EFEFF2',
    borderRadius: '16px',
    padding: '14px 18px',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.02)',
  },
  denemeThemeIconBox: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    backgroundColor: '#F2F2F5',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  denemeThemeTitle: {
    fontSize: '15px',
    fontWeight: 700,
    color: '#111',
    letterSpacing: '-0.2px',
  },
  denemeThemeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: '11px',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: '6px',
    backgroundColor: '#F2F2F5',
    color: '#555',
  },
  denemeThemeDesc: {
    fontSize: '12.5px',
    color: '#666',
    marginTop: '3px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  denemeThemeBtn: {
    backgroundColor: '#111111',
    color: '#FFFFFF',
    borderRadius: '10px',
    padding: '9px 16px',
    fontSize: '13px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexShrink: 0,
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.08)',
  },
  mobileBottomNav: {
    display: 'none',
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    height: '64px',
    backgroundColor: '#FFFFFF',
    borderTop: '1px solid #EFEFF2',
    justifyContent: 'space-around',
    alignItems: 'center',
    zIndex: 1000,
    boxShadow: '0 -2px 10px rgba(0,0,0,0.05)',
  },
  mobileBottomNavItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'none',
    border: 'none',
    padding: '6px 0',
    cursor: 'pointer',
    gap: '3px',
  },
  mobileBottomNavItemActive: {},
  mobileBottomNavLabel: {
    fontSize: '11px',
    letterSpacing: '-0.2px',
  },
};